set_property PACKAGE_PIN E19 [get_ports sys_diff_clock_clk_p]
set_property IOSTANDARD LVDS [get_ports sys_diff_clock_clk_p]
set_property PACKAGE_PIN E18 [get_ports sys_diff_clock_clk_n]
set_property IOSTANDARD LVDS [get_ports sys_diff_clock_clk_n]

set_property PACKAGE_PIN AV40 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports reset]

set_property PACKAGE_PIN AU36 [get_ports rs232_uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports rs232_uart_rxd]
set_property PACKAGE_PIN AU33 [get_ports {rs232_uart_txd}]
set_property IOSTANDARD LVCMOS18 [get_ports {rs232_uart_txd}]
#set_property PACKAGE_PIN AM39 [get_ports {led[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
#set_property PACKAGE_PIN AN39 [get_ports {led[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
#set_property PACKAGE_PIN AR37 [get_ports {led[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
#set_property PACKAGE_PIN AT37 [get_ports {led[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]
#set_property PACKAGE_PIN AR35 [get_ports {led[4]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {led[4]}]
#set_property PACKAGE_PIN AP41 [get_ports {led[5]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {led[5]}]
#set_property PACKAGE_PIN AP42 [get_ports {led[6]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {led[6]}]
#set_property PACKAGE_PIN AU39 [get_ports {led[7]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {led[7]}]
